-- MySQL Script generated by MySQL Workbench
-- Thu Oct  3 14:40:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`director` ;

CREATE TABLE IF NOT EXISTS `mydb`.`director` (
  `iddirector` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  PRIMARY KEY (`iddirector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CEO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CEO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CEO` (
  `idCEO` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  PRIMARY KEY (`idCEO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`studio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`studio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`studio` (
  `idstudio` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `CEO_idCEO` INT NOT NULL,
  PRIMARY KEY (`idstudio`, `CEO_idCEO`),
  INDEX `fk_studio_CEO1_idx` (`CEO_idCEO` ASC) VISIBLE,
  CONSTRAINT `fk_studio_CEO1`
    FOREIGN KEY (`CEO_idCEO`)
    REFERENCES `mydb`.`CEO` (`idCEO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`composer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`composer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`composer` (
  `idcomposer` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`idcomposer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movie` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Year` INT NULL,
  `Country` VARCHAR(45) NULL,
  `director_iddirector` INT NOT NULL,
  `studio_idstudio` INT NOT NULL,
  `composer_idcomposer` INT NOT NULL,
  PRIMARY KEY (`Id`, `director_iddirector`, `studio_idstudio`),
  INDEX `fk_movie_director_idx` (`director_iddirector` ASC) VISIBLE,
  INDEX `fk_movie_studio1_idx` (`studio_idstudio` ASC) VISIBLE,
  INDEX `fk_movie_composer1_idx` (`composer_idcomposer` ASC) VISIBLE,
  CONSTRAINT `fk_movie_director`
    FOREIGN KEY (`director_iddirector`)
    REFERENCES `mydb`.`director` (`iddirector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_studio1`
    FOREIGN KEY (`studio_idstudio`)
    REFERENCES `mydb`.`studio` (`idstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_composer1`
    FOREIGN KEY (`composer_idcomposer`)
    REFERENCES `mydb`.`composer` (`idcomposer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`actor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`actor` (
  `idactor` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`idactor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`theatre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`theatre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`theatre` (
  `idtheatre` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`idtheatre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`showing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`showing` ;

CREATE TABLE IF NOT EXISTS `mydb`.`showing` (
  `idshowing` INT NOT NULL,
  `ticket_price` INT NULL,
  `date` DATE NULL,
  `movie_Id` INT NOT NULL,
  PRIMARY KEY (`idshowing`),
  INDEX `fk_showing_movie1_idx` (`movie_Id` ASC) VISIBLE,
  CONSTRAINT `fk_showing_movie1`
    FOREIGN KEY (`movie_Id`)
    REFERENCES `mydb`.`movie` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reviewer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reviewer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reviewer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rating` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rating` (
  `idrating` INT NOT NULL,
  `content` VARCHAR(100) NULL,
  `score` INT NULL,
  `movie_Id` INT NOT NULL,
  `movie_director_iddirector` INT NOT NULL,
  `movie_studio_idstudio` INT NOT NULL,
  `reviewer_id` INT NOT NULL,
  PRIMARY KEY (`idrating`),
  INDEX `fk_rating_movie1_idx` (`movie_Id` ASC, `movie_director_iddirector` ASC, `movie_studio_idstudio` ASC) VISIBLE,
  INDEX `fk_rating_reviewer1_idx` (`reviewer_id` ASC) VISIBLE,
  CONSTRAINT `fk_rating_movie1`
    FOREIGN KEY (`movie_Id` , `movie_director_iddirector` , `movie_studio_idstudio`)
    REFERENCES `mydb`.`movie` (`Id` , `director_iddirector` , `studio_idstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_reviewer1`
    FOREIGN KEY (`reviewer_id`)
    REFERENCES `mydb`.`reviewer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`awards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`awards` ;

CREATE TABLE IF NOT EXISTS `mydb`.`awards` (
  `idawards` INT NOT NULL,
  `awardname` VARCHAR(45) NULL,
  `year` INT NULL,
  `movie_Id` INT NOT NULL,
  `movie_director_iddirector` INT NOT NULL,
  `movie_studio_idstudio` INT NOT NULL,
  PRIMARY KEY (`idawards`),
  INDEX `fk_awards_movie1_idx` (`movie_Id` ASC, `movie_director_iddirector` ASC, `movie_studio_idstudio` ASC) VISIBLE,
  CONSTRAINT `fk_awards_movie1`
    FOREIGN KEY (`movie_Id` , `movie_director_iddirector` , `movie_studio_idstudio`)
    REFERENCES `mydb`.`movie` (`Id` , `director_iddirector` , `studio_idstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie_has_actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movie_has_actor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movie_has_actor` (
  `movie_Id` INT NOT NULL,
  `actor_idactor` INT NOT NULL,
  PRIMARY KEY (`movie_Id`, `actor_idactor`),
  INDEX `fk_movie_has_actor_actor1_idx` (`actor_idactor` ASC) VISIBLE,
  INDEX `fk_movie_has_actor_movie1_idx` (`movie_Id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_has_actor_movie1`
    FOREIGN KEY (`movie_Id`)
    REFERENCES `mydb`.`movie` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_has_actor_actor1`
    FOREIGN KEY (`actor_idactor`)
    REFERENCES `mydb`.`actor` (`idactor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie_has_theatre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movie_has_theatre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movie_has_theatre` (
  `movie_Id` INT NOT NULL,
  `theatre_idtheatre` INT NOT NULL,
  PRIMARY KEY (`movie_Id`, `theatre_idtheatre`),
  INDEX `fk_movie_has_theatre_theatre1_idx` (`theatre_idtheatre` ASC) VISIBLE,
  INDEX `fk_movie_has_theatre_movie1_idx` (`movie_Id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_has_theatre_movie1`
    FOREIGN KEY (`movie_Id`)
    REFERENCES `mydb`.`movie` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_has_theatre_theatre1`
    FOREIGN KEY (`theatre_idtheatre`)
    REFERENCES `mydb`.`theatre` (`idtheatre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
